spring:
  profiles:
    active: dev
  data:
    mongodb:
      port: ${DB_PORT}
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?authSource=admin

cronValue: ${CRON_EXPRESSION}
